name: check rustfmt

on:
  push:
    branches: ["**"]

permissions: {}

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - uses: dtolnay/rust-toolchain@7b1c307e0dcbda6122208f10795a713336a9b35a # master
        with:
          toolchain: stable
          components: rustfmt
      - name: Run rustfmt
        run: cargo fmt --all --check -- --color=always
