name: check rustfmt

on:
  push:
    branches: ["**"]

permissions: {}

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run rustfmt
        run: cargo fmt --all --check -- --color=always
