name: check rustfmt

on:
  push:
    branches: ["**"]

permissions: {}

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: dtolnay/rust-toolchain@315e265cd78dad1e1dcf3a5074f6d6c47029d5aa # master
        with:
          toolchain: stable
          components: rustfmt
      - name: Run rustfmt
        run: cargo fmt --all --check -- --color=always
